config/routes.rb
Rails.application.routes.draw do

  # get 'session/home'
  root "session#home"
  resources :items, except: [:show]
  get '/items/most_popular/', to: 'items#most_popular_items'

  resources :orders, except: [:new]
  resources :users
  resources :order_items
  resources :users,only: [:show] do
    resources :orders, only:[:new, :show, :index]
  end

  get 'users/:id/orders', to: 'users#order_index'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'

  
  delete '/logout', to: 'session#destroy'

  # GOOGLE Login
  get '/auth/google_oauth2/callback', to: 'session#oauth_login'
  # FACEBOOK LOGIN
  get '/auth/facebook/callback' => 'session#oauth_login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :username, on: [:create, :update], message: "can't be blank"
    validates_uniqueness_of :username, on: :create, message: "must be unique"
    has_many :orders, :dependent => :delete_all
    has_many :order_items, through: :orders
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user=User.new
    end

    def create
            @user = User.new(user_params)
            if @user.save
            flash[:success] = "Account created, you can now login"
            redirect_to root_path
        else
            flash[:alert] = "Something wasn't quite right!"
            render 'new'
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to root_path if !@user
    end

    def order_index
        @orders = current_user.orders
        render template: 'orders/index'
    end

    def index
        @users = User.all
        @order = Order.pending
    end

    def edit
        if admin
            @user = User.find(params[:id])
        else
            @user = User.find(params[:id])
            if @user != current_user
                flash[:error] = "Only and admin can change other users details"
                redirect_to user_path(current_user)
            end
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          flash[:success] = "User was successfully updated"
          redirect_to @user
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        if @user.destroy
            flash[:success] = 'User was successfully deleted.'
            redirect_to users_url
        else
            flash[:error] = 'Something went wrong'
            redirect_to users_url
        end
    end
    
    
    
    

    private

    def user_params
        params.require(:user).permit(:name, :username, :password, :email, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<p></p>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h3>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<p></p>

<%= bootstrap_form_for(@user) do |f| %>
    <p>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.text_field :username %>
    </p>
    <p>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.email_field :email %>
    </p>
    <% if (current_user && current_user.admin) %>
        <p>
            <%= f.check_box :admin %>
        </p>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render  "form" %>

app/views/users/index.html.erb
<table class="table">
    <thead>
        <tr>
            <th scope="">Name</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <th scope="row"><%= user.name %></th>
                <th scope="row"><%= user.username %></th>
                <th scope="row"><%= user.email %></th>
                <th>
                    <% if current_user.admin %>
                        <%= link_to  "Edit user profile", edit_user_path(user), class: "btn btn-success btn-sm" %>
                        <%= link_to  "Delete this user", user_path(user), method: :delete, class: "btn btn-danger btn-sm" %>
                    <%end%>
                </th>
                <td>
                    <% if user.admin %>
                        (admin)
                    <% else %>
                        <%= link_to  "Orders", user_orders_path(user) %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<%= render  "form" %>

app/views/users/show.html.erb
<p><%= @user.name %> welcome to your page.</p>

<p>Your details:</p>
Name: <%= @user.name %><br>
Username: <i><%= @user.username %></i><br>
Email: <%= @user.email %><br>
Your role: <i><%= @user.admin ? "admin" : "user" %></i><br>
<br>
<%= link_to  "Edit your details", edit_user_path %>