config/routes.rb
Rails.application.routes.draw do

  # get 'session/home'
  root "session#home"
  resources :items, except: [:show]
  get '/items/most_popular/', to: 'items#most_popular_items'

  resources :orders, except: [:new]
  resources :users
  resources :order_items
  resources :users,only: [:show] do
    resources :orders, only:[:new, :show, :index]
  end

  get 'users/:id/orders', to: 'users#order_index'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'

  
  delete '/logout', to: 'session#destroy'

  # GOOGLE Login
  get '/auth/google_oauth2/callback', to: 'session#oauth_login'
  # FACEBOOK LOGIN
  get '/auth/facebook/callback' => 'session#oauth_login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items, :dependent => :delete_all
    has_many :items, through: :order_items
    belongs_to :user
    before_save :set_total_price

    scope :pending, -> { where(approved: false) }
    

    def total
        order_items.collect {|order_item| order_item.valid? ? order_item.item.price*order_item.quantity : 0}.sum
    end

	private
		def set_total_price
			self[:total_price] = total
        end
        
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
		if admin
			if params[:user_id]
				@user=User.find(params[:user_id])
				@orders = @user.orders.where(approved: false).order("created_at DESC")
			else
				@orders = Order.all.order("created_at DESC")
			end
		else
			@orders = current_user.orders.order("created_at DESC")
		end
    end

    def show
		@order = Order.find_by(id: params[:id])
		if logged_in? && (current_user.orders.include?(@order)  || admin)
			session[:order_id] = @order.id
			render 'show'
		else
			flash[:error] = "Illegal action, you were redirect to the homepage"
			redirect_to root_path
		end
        
    end

	def update
		@order = Order.find(params[:id])
		#only path here is 'approve order'
		@order.approved = true
		if @order.save
		  flash[:success] = "Order was successfully updated"
		  redirect_to @order
		else
		  flash[:error] = "Something went wrong"
		  render 'edit'
		end
	end
	
	def edit
		@order = Order.find_by(id: params[:id])
		if logged_in? && current_user.orders.include?(@order)
			@order_items_size = @order.order_items.size
			@order_items = @order.order_items.sort {|a, b| a.item.name <=> b.item.name}
			render 'edit'
		else
			flash[:error] = "Illegal action, you were redirect to the homepage"
			redirect_to root_path
		end
	end

	def new
		create
	end
	

	def create
		if logged_in?
			session[:order_id] = nil
			@order = Order.new
			if current_user.admin
				@order.user = User.find_by(id: params[:user_id])
				@order.save!
				session[:order_id] = @order.id
			end
			redirect_to items_path
		else
			flash[:alert] = "You need to be signed in to add a new order"
		end
	end

	def destroy
		@order = Order.find(params[:id])
		if @order.destroy
			flash[:success] = 'Order was successfully deleted.'
			redirect_to orders_url
		else
			flash[:error] = 'Something went wrong'
			redirect_to orders_url
		end
	end
	

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order_header.html.erb
<p></p>
<p>Order no.: <%= @order.id %>,  status: <%= order_approved? ? 'Approved' : 'Pending' %></p>
<p><h3>Order total: <%= number_to_currency(@order.total_price) %></h3></p>

app/views/orders/edit.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= render :partial => 'order_header' %>

<% if @order_items_size>0 %>
	<% @order_items.each do |oitem| %>
        <div class="row">
        <div class="col-sm-2">
		    <strong><%= oitem.item.name %></strong>
        </div>
        <div class="col-md-8">
            <%= form_for(oitem, remote: true) do |f| %>
            <div class="row">
		        <%= f.hidden_field :item_id, value: oitem.item.id %>
                <div class="col">                
			    <%= '%.2f' % oitem.item.price %>
                </div>
                <div class="col">
                <%= f.text_field :quantity, value: oitem.quantity, min: 1 %>
                </div>
	            <div class="btn-group">
                <div class="col">
                    <%= f.submit "Update", class: 'btn btn-primary btn-sm' %>
                </div>
                <div class="col">
                    <%= link_to "Delete", oitem, method: :delete, remote: true, class: 'btn btn-danger btn-sm'  %>
                </div>
                </div>
                <div class="col">
                <span>Total Price: <%=  '%.2f' % (oitem.item.price * oitem.quantity) %></span>
                </div>
		    <% end %>	
            </div>
        </div>	
		</div>
        <br>
	<% end %>
<% else %>
    <h5>This order has no items added yet!</h5>
<% end %>
</div>

app/views/orders/index.html.erb
<% if admin && @user %>
    <p>Order(s) in name of: <%= @user.name %></p>
    <p><%= link_to  " Create new order", new_user_order_path %></p>
<% elsif !admin %>
    <p><%= link_to  "Create new order", new_order_path %>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Order #</th>
            <th scope="col">Ordered by</th>
            <th scope="col">Status</th>
            <th scope="col">Created</th>
            <th scope="col">Order total</th>
        </tr>
    </thead>
    <tbody>
        <%@orders.each do |order| %>
            <tr>
                <th scope="row"><%= order.id%></th>
                <td><%= order.user.name %></td>
                <td><%= order.approved ? 'Approved' : 'Pending' %></td>
                <td><%= order.created_at %></td>
                <td><%= number_to_currency(order.total_price) %>
                <td><%= link_to  "order details", order_path(order), class: "btn btn-primary btn-sm" %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/orders/show.html.erb
<%= render :partial => 'order_header' %>
<p>
<% if !order_approved? %>
    <% if admin %>
        Order in name of: <%= @order.user.name %>&emsp;
        <span><%= link_to  "Approve this order", order_path, method: :patch, class: "btn btn-success btn-sm" %></span>  
    <% else %>
        <span><%= link_to  "Edit this order", edit_order_path(@order), class: "btn btn-primary btn-sm" %></span> 
    <% end %>
    
    <span><%= link_to  "Delete this order", order_path, method: :delete, class: "btn btn-danger btn-sm" %></span>
<% end %>
</p>

<table class="table">
    <thead>
        <tr>
            <th scope="">Item</th>
            <th scope="col">quantity</th>
            <th scope="col">Item Price</th>
            <th scope="col">Total Price</th>
        </tr>
    </thead>
    <tbody>
        <% @order.order_items.each do |oi| %>
            <tr>
                <th scope="row"><%= oi.item.name %></th>
                <td><%= oi.quantity %></td>
                <td><%= number_to_currency(oi.item.price) %></td>
                <td><%= number_to_currency(oi.item.price * oi.quantity) %></td>
                <td></td>
            </tr>
        <% end %>
    </tbody>
</table>