config/routes.rb
Rails.application.routes.draw do

  # get 'session/home'
  root "session#home"
  resources :items, except: [:show]
  get '/items/most_popular/', to: 'items#most_popular_items'

  resources :orders, except: [:new]
  resources :users
  resources :order_items
  resources :users,only: [:show] do
    resources :orders, only:[:new, :show, :index]
  end

  get 'users/:id/orders', to: 'users#order_index'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'

  
  delete '/logout', to: 'session#destroy'

  # GOOGLE Login
  get '/auth/google_oauth2/callback', to: 'session#oauth_login'
  # FACEBOOK LOGIN
  get '/auth/facebook/callback' => 'session#oauth_login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :order_items
    has_many :orders, through: :order_items
    
    validates_presence_of :name, on: :create, message: "can't be blank"
    validates_presence_of :description, on: :create, message: "can't be blank"
    validates_presence_of :price, on: :create, message: "can't be blank"
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        if !params[:search]
            @items = Item.all.order(:name)
        else 
            @items = Item.where("lower(name) LIKE ?",  "%" + params[:search].downcase + "%")
        end
        @order_item = current_order.order_items.new
    end

    def new
        if admin
            @item = Item.new
        else
            flash[:alert] = "Only an admin can add items!"
            redirect_to items_path
        end
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            flash[:success] = "Item successfully created"
            redirect_to items_path
        else
            flash[:error] = "Something went wrong"
            render 'new'
        end
    end

    def edit
        if admin
            @item = Item.find_by(id: params[:id])
        else
            flash[:alert] = "Only an admin can change items"
            redirect_to items_path
        end
    end

    def update
        @item = Item.find_by(id: params[:id])
        if @item.update(item_params)
          flash[:success] = "Item was successfully updated"
          redirect_to items_path
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
    def most_popular_items
        @popular_items_top5 = OrderItem.popular_sort.first(5).map{|i| Item.find_by(id: i)}
        @order_item = OrderItem.new
    end

    private

    def item_params
        params.require(:item).permit(:name, :description, :price, :available)
    end
    
    
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<br>
<% if !@item.nil? && @item.errors.any? %>
	<ul>
		<% @item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= bootstrap_form_for(@item) do |f| %>
    <p><%= f.text_field :name %></p>
    <p><%= f.text_area :description %></p>
    <p><%= f.text_field :price %></p>
    <p><%= f.check_box :available %></p>
    <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h4>Edit Item</h4>
<%= render 'form' %>

app/views/items/index.html.erb
<p><%= link_to  "Top 5, most ordered items", items_most_popular_path %></p>
<% if session[:order_id] %>
    You are working on: <%= link_to  "Order #{session[:order_id]}", order_path(session[:order_id]) %>
<% end %>

<p></p>
<h4>Search items</h4>
<%= form_tag(items_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ('Search') %>
<% end %>
<p><h4>Items available</h4></p>
<% if admin %>
	<%= link_to  "Add item", new_item_path %>
<% end %>
<p></p>
<p></p>
<% @items.each do |item| %>
	<div>
		<div class="row">
			<div class="col-sm-2">
				<h5><%= item.name %></h5>
			</div>
            <div class="col-sm-3">
                <h6><%= item.description %></h6>
            </div>
            <div class="col-sm-7">
				<%= form_for(@order_item, remote: true) do |f| %>
                    <div class="row">
					    <%= f.hidden_field :item_id, value: item.id %>
					    <div class="col-sm-2">
                            <h5><%= number_to_currency(item.price) %></h5>
                        </div>
                        
					    <div class="form-group">
                        
                            <div class="col-auto">&emsp;
						        <%= f.text_field :quantity, value: 1, min: 1 %>
                            </div>
					    
                        </div>
                        <div class="col-auto">
						<% if item.available %>
					    	<%= f.submit "Order", class: 'btn btn-primary btn-sm' %>
						<% else %>
							<button type="button" class="btn btn-danger btn-sm" href="#">Out of stock</button>
						<% end %>
						<% if admin %>
							<%= link_to "Edit", edit_item_path(item), class: "btn btn-success btn-sm" %>
						<% end %>
                        </div>
                    </div>
				<% end %>
			</div>
		</div>
	</div>
    
<% end %>

app/views/items/most_popular.html.erb
Most popular items:
<div class="row">
	<div class="col-sm-2">
		<h5><%= @most_popular_item.name %></h5>
	</div>
    <div class="col-sm-3">
        <h6><%= @most_popular_item.description %></h6>
    </div>
	<div class="col-sm-2">
        <h5><%= number_to_currency(@most_popular_item.price) %></h5>
    </div>
</div>

app/views/items/most_popular_items.html.erb
<p></p>
<p><h3>Top 5 most ordered items</h3></p>
<% @popular_items_top5.each do |item| %>
<div>
		<div class="row">
			<div class="col-sm-2">
				<h5><%= item.name %></h5>
			</div>
            <div class="col-sm-3">
                <h6><%= item.description %></h6>
            </div>
            <div class="col-sm-7">
				<%= form_for(@order_item, remote: true) do |f| %>
                    <div class="row">
					    <%= f.hidden_field :item_id, value: item.id %>
					    <div class="col-sm-2">
                            <h5><%= number_to_currency(item.price) %></h5>
                        </div>
                        
					    <div class="form-group">
                        
                            <div class="col-auto">&emsp;
						        <%= f.text_field :quantity, value: 1, min: 1 %>
                            </div>
					    
                        </div>
                        <div class="col-auto">
						<% if item.available %>
					    	<%= f.submit "Order", class: 'btn btn-primary btn-sm' %>
						<% else %>
							<button type="button" class="btn btn-danger btn-sm" href="#">Out of stock</button>
						<% end %>
						<% if admin %>
							<%= link_to "Edit", edit_item_path(item), class: "btn btn-success btn-sm" %>
						<% end %>
                        </div>
                    </div>
				<% end %>
			</div>
		</div>
	</div>
<%end%>

app/views/items/new.html.erb
<h4>New Item</h4>
<%= render 'form' %>